### PR TITLE
Added Curated Resources by prog community

### PR DESCRIPTION
**Pull request by rohduggal**
https://hackr.io/tutorials/learn-bootstrap

### CODE REVIEW

**Comment by shadowcodex** [comment]
What does python have to do with bootstrap?

**Comment by rohduggal** [comment]
Srry about that. I have resubmitted, please check.

**Comment by shadowcodex** [comment]
@therebelrobot what are your thoughts on this? Are tutorial aggregators like this something we want on the awesome page? or would we rather have direct links to tutorials?

**Comment by rohduggal** [comment]
The resources that i've mentioned are recommended/voted by the developers.

**Comment by shadowcodex** [comment]
No i'd like direct tutorial links from now on. Closing.

**Pull request closed without merging**
